$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: mdg_assembler_environment
version: 1
description: "Environment for MDG Technology File Assembler"

docker:
  image: python:3.8
