$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: uid_generator
display_name: UID Generator
version: 1

inputs:
  use_uuid:
    type: boolean
    default: true

settings:
  prefix: "UID"
  initial_count: 1000

environment:
  name: uid_generator_environment
  version: 1
  description: "Environment for UID Generator"
  os_type: linux
  conda:
    conda_dependencies:
      channels:
        - anaconda
        - conda-forge
      dependencies:
        - python=3.8
        - pip
        - pip:
            - numpy  # Add any additional dependencies
  environment_variables:
    GENERATION_MODE: "UUID"

command: >-
  python UIDGen.py --use_uuid ${{inputs.use_uuid}}
