$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: interdependency_mapper_environment
version: 1
description: "Environment for Interdependency Mapper"

docker:
  image: python:3.8
