$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: resource_mapper_environment
version: 1
description: "Environment for Azure ML & Terraform Resource Mapper"

docker:
  image: python:3.8
