$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: toolbox_customizer_environment
version: 1
description: "Environment for Modeling Toolbox Customizer"

docker:
  image: python:3.8
