$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: visio_planner_environment
version: 1
description: "Environment for Visualization and Access Control Planner"

docker:
  image: python:3.8
