$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: model_fragment_creator_environment
version: 1
description: "Environment for Reusable Model Fragment Creator"

docker:
  image: python:3.8
