$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: model_generator_environment
version: 1
description: "Environment for Starter Model Generator"

docker:
  image: python:3.8
