$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: mdg_controller_environment
version: 1
description: "Environment for MDG Integration Controller"

docker:
  image: python:3.8
