$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: data_validator_environment
version: 1
description: "Environment for Data Validation"

docker:
  image: python:3.8

conda:
  conda_dependencies:
    channels:
      - anaconda
    dependencies:
      - python=3.8
      - pandas
