$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: script_integrator_environment
version: 1
description: "Environment for Script and Extension Integrator"

docker:
  image: python:3.8
