$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: uid_generator_environment
version: 1
description: "Environment for UID Generator"

docker:
  image: python:3.8 # Or any other image that suits your needs
