$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: config_manager_environment
version: 1
description: "Environment for Configuration Management"

docker:
  image: python:3.8

conda:
  conda_dependencies:
    channels:
      - anaconda
    dependencies:
      - python=3.8
