$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: architecture_mapper_environment
version: 1
description: "Environment for Integrated Architecture Mapper"

docker:
  image: python:3.8
