$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: diagram_designer_environment
version: 1
description: "Environment for Custom Diagram Designer"

docker:
  image: python:3.8
