$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: stereotype_definer_environment
version: 1
description: "Environment for Stereotype Definer"

docker:
  image: python:3.8
